# Generated by Django 3.1.7 on 2021-03-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('', ''), (0, 'performed'), (1, 'paid')], max_length=15),
        ),
    ]
