# Generated by Django 3.1.7 on 2021-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210309_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[(-1, 'added'), (0, 'performed'), (1, 'paid')], max_length=15),
        ),
    ]
