# Generated by Django 3.1.7 on 2021-03-09 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
