# Generated by Django 3.1.7 on 2021-03-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0004_remove_staff_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='group',
        ),
        migrations.AddField(
            model_name='staff',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
